steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cloud-run-cd/github.com/massimiliano67-it/apisingolang:$COMMIT_SHA', '-f', 'apibasic/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cloud-run-cd/github.com/massimiliano67-it/apisingolang:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'apibasic', '--image=gcr.io/cloud-run-cd/github.com/massimiliano67-it/apisingolang:$COMMIT_SHA','--platform=managed', '--region=us-central1']
